import { useEffect, useState } from 'react';
import {
  Box,
  Typography,
  Card,
  CardContent,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  IconButton,
  TextField,
  Button,
  TablePagination,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Grid,
  Chip,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Alert,
} from '@mui/material';
import { Add, CheckCircle, Refresh, Edit, Delete, Upload } from '@mui/icons-material';
import api from '../../services/api';
import { toast } from 'react-toastify';

const RecoveryTransactionsPage = () => {
  const [transactions, setTransactions] = useState([]);
  const [clients, setClients] = useState([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState('');
  const [clientFilter, setClientFilter] = useState('');
  const [autoGeneratedFilter, setAutoGeneratedFilter] = useState('');
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(10);
  const [totalCount, setTotalCount] = useState(0);
  const [openDialog, setOpenDialog] = useState(false);
  const [openEditDialog, setOpenEditDialog] = useState(false);
  const [openPaymentDialog, setOpenPaymentDialog] = useState(false);
  const [openBulkDialog, setOpenBulkDialog] = useState(false);
  const [selectedTransaction, setSelectedTransaction] = useState(null);
  const [formData, setFormData] = useState({
    clientId: '',
    amount: '',
    dueDate: '',
    notes: '',
  });
  const [editFormData, setEditFormData] = useState({
    amount: '',
    dueDate: '',
    notes: '',
  });
  const [paymentData, setPaymentData] = useState({
    paymentMethod: 'manual',
    paymentReference: '',
  });
  const [bulkData, setBulkData] = useState([
    { clientId: '', amount: '', dueDate: '', notes: '' },
  ]);

  useEffect(() => {
    fetchTransactions();
    fetchClients();
  }, [page, rowsPerPage, statusFilter, clientFilter, autoGeneratedFilter]);

  const fetchTransactions = async () => {
    setLoading(true);
    try {
      const response = await api.get('/business-owner/recovery-transactions', {
        params: {
          page: page + 1,
          limit: rowsPerPage,
          status: statusFilter,
          clientId: clientFilter,
        },
      });
      setTransactions(response.data.data.transactions);
      setTotalCount(response.data.data.pagination.total);
    } catch (error) {
      console.error('Failed to fetch transactions:', error);
    } finally {
      setLoading(false);
    }
  };

  const fetchClients = async () => {
    try {
      const response = await api.get('/business-owner/clients', {
        params: { limit: 100 },
      });
      setClients(response.data.data.clients);
    } catch (error) {
      console.error('Failed to fetch clients:', error);
    }
  };

  const handleOpenDialog = () => {
    setFormData({
      clientId: '',
      amount: '',
      dueDate: '',
      notes: '',
    });
    setOpenDialog(true);
  };

  const handleCloseDialog = () => {
    setOpenDialog(false);
  };

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleEditChange = (e) => {
    setEditFormData({ ...editFormData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await api.post('/business-owner/recovery-transactions', formData);
      toast.success('Transaction created successfully');
      handleCloseDialog();
      fetchTransactions();
    } catch (error) {
      console.error('Failed to create transaction:', error);
    }
  };

  const handleOpenEdit = (transaction) => {
    setSelectedTransaction(transaction);
    setEditFormData({
      amount: transaction.amount,
      dueDate: transaction.dueDate ? transaction.dueDate.split('T')[0] : '',
      notes: transaction.notes || '',
    });
    setOpenEditDialog(true);
  };

  const handleEditSubmit = async (e) => {
    e.preventDefault();
    try {
      await api.put(`/business-owner/recovery-transactions/${selectedTransaction.id}`, editFormData);
      toast.success('Transaction updated successfully');
      setOpenEditDialog(false);
      fetchTransactions();
    } catch (error) {
      console.error('Failed to update transaction:', error);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Are you sure you want to delete this transaction?')) {
      try {
        await api.delete(`/business-owner/recovery-transactions/${id}`);
        toast.success('Transaction deleted successfully');
        fetchTransactions();
      } catch (error) {
        console.error('Failed to delete transaction:', error);
      }
    }
  };

  const handleOpenPaymentDialog = (transaction) => {
    setSelectedTransaction(transaction);
    setPaymentData({
      paymentMethod: 'manual',
      paymentReference: '',
    });
    setOpenPaymentDialog(true);
  };

  const handleClosePaymentDialog = () => {
    setOpenPaymentDialog(false);
    setSelectedTransaction(null);
  };

  const handleMarkPaid = async () => {
    try {
      await api.patch(
        `/business-owner/recovery-transactions/${selectedTransaction.id}/mark-paid`,
        paymentData
      );
      toast.success('Payment marked as paid successfully!');
      handleClosePaymentDialog();
      fetchTransactions();
    } catch (error) {
      console.error('Failed to mark payment:', error);
    }
  };

  const handleAddBulkRow = () => {
    setBulkData([...bulkData, { clientId: '', amount: '', dueDate: '', notes: '' }]);
  };

  const handleRemoveBulkRow = (index) => {
    const newData = bulkData.filter((_, i) => i !== index);
    setBulkData(newData);
  };

  const handleBulkChange = (index, field, value) => {
    const newData = [...bulkData];
    newData[index][field] = value;
    setBulkData(newData);
  };

  const handleBulkSubmit = async () => {
    try {
      const validTransactions = bulkData.filter(t => t.clientId && t.amount);
      if (validTransactions.length === 0) {
        toast.error('Please provide at least one valid transaction');
        return;
      }

      await api.post('/business-owner/recovery-transactions/bulk', {
        transactions: validTransactions,
      });
      toast.success(`${validTransactions.length} transactions created successfully!`);
      setOpenBulkDialog(false);
      setBulkData([{ clientId: '', amount: '', dueDate: '', notes: '' }]);
      fetchTransactions();
    } catch (error) {
      console.error('Failed to create bulk transactions:', error);
    }
  };

  return (
    <div>
      <Box className="mb-6">
        <Typography variant="h4" fontWeight="bold" gutterBottom>
          Recovery Transactions
        </Typography>
        <Typography variant="body1" color="text.secondary">
          Manage recovery transactions and payments
        </Typography>
      </Box>

      <Card>
        <CardContent>
          <Box className="flex justify-between items-center mb-4 flex-wrap gap-2">
            <Box className="flex gap-2 flex-wrap">
              <FormControl size="small" sx={{ minWidth: 150 }}>
                <InputLabel>Status</InputLabel>
                <Select
                  value={statusFilter}
                  label="Status"
                  onChange={(e) => setStatusFilter(e.target.value)}
                >
                  <MenuItem value="">All</MenuItem>
                  <MenuItem value="pending">Pending</MenuItem>
                  <MenuItem value="paid">Paid</MenuItem>
                </Select>
              </FormControl>
              <FormControl size="small" sx={{ minWidth: 200 }}>
                <InputLabel>Client</InputLabel>
                <Select
                  value={clientFilter}
                  label="Client"
                  onChange={(e) => setClientFilter(e.target.value)}
                >
                  <MenuItem value="">All Clients</MenuItem>
                  {clients.map((client) => (
                    <MenuItem key={client.id} value={client.id}>
                      {client.name}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
              <FormControl size="small" sx={{ minWidth: 180 }}>
                <InputLabel>Source</InputLabel>
                <Select
                  value={autoGeneratedFilter}
                  label="Source"
                  onChange={(e) => setAutoGeneratedFilter(e.target.value)}
                >
                  <MenuItem value="">All Sources</MenuItem>
                  <MenuItem value="auto">Auto-Generated</MenuItem>
                  <MenuItem value="manual">Manual</MenuItem>
                </Select>
              </FormControl>
            </Box>
            <Box className="flex gap-2">
              <Button
                variant="outlined"
                startIcon={<Refresh />}
                onClick={fetchTransactions}
                size="small"
              >
                Refresh
              </Button>
              <Button
                variant="outlined"
                startIcon={<Upload />}
                onClick={() => setOpenBulkDialog(true)}
                size="small"
              >
                Bulk Add
              </Button>
              <Button
                variant="contained"
                startIcon={<Add />}
                onClick={handleOpenDialog}
                size="small"
              >
                Add Transaction
              </Button>
            </Box>
          </Box>

          <TableContainer component={Paper} elevation={0}>
            <Table>
              <TableHead>
                <TableRow>
                  <TableCell>Client</TableCell>
                  <TableCell align="right">Amount</TableCell>
                  <TableCell>Status</TableCell>
                  <TableCell>Source</TableCell>
                  <TableCell>Due Date</TableCell>
                  <TableCell>Paid Date</TableCell>
                  <TableCell>Notes</TableCell>
                  <TableCell align="center">Actions</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={8} align="center">
                      Loading...
                    </TableCell>
                  </TableRow>
                ) : transactions.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} align="center">
                      No transactions found
                    </TableCell>
                  </TableRow>
                ) : (
                  transactions.map((transaction) => {
                    const isAutoGenerated = transaction.notes?.includes('Auto-generated from schedule');
                    return (
                    <TableRow key={transaction.id} hover>
                      <TableCell>{transaction.client.name}</TableCell>
                      <TableCell align="right">
                        <Typography fontWeight="bold">PKR {transaction.amount.toFixed(2)}</Typography>
                      </TableCell>
                      <TableCell>
                        <Chip
                          label={transaction.status}
                          color={transaction.status === 'paid' ? 'success' : 'warning'}
                          size="small"
                        />
                      </TableCell>
                      <TableCell>
                        {isAutoGenerated ? (
                          <Chip
                            label="Auto"
                            color="info"
                            size="small"
                            icon={<Refresh />}
                          />
                        ) : (
                          <Chip
                            label="Manual"
                            variant="outlined"
                            size="small"
                          />
                        )}
                      </TableCell>
                      <TableCell>
                        {transaction.dueDate
                          ? new Date(transaction.dueDate).toLocaleDateString()
                          : '-'}
                      </TableCell>
                      <TableCell>
                        {transaction.paidDate
                          ? new Date(transaction.paidDate).toLocaleDateString()
                          : '-'}
                      </TableCell>
                      <TableCell>{transaction.notes || '-'}</TableCell>
                      <TableCell align="center">
                        {transaction.status === 'pending' && (
                          <>
                            <IconButton
                              size="small"
                              color="primary"
                              onClick={() => handleOpenEdit(transaction)}
                              title="Edit"
                            >
                              <Edit />
                            </IconButton>
                            <IconButton
                              size="small"
                              color="success"
                              onClick={() => handleOpenPaymentDialog(transaction)}
                              title="Mark Paid"
                            >
                              <CheckCircle />
                            </IconButton>
                            <IconButton
                              size="small"
                              color="error"
                              onClick={() => handleDelete(transaction.id)}
                              title="Delete"
                            >
                              <Delete />
                            </IconButton>
                          </>
                        )}
                      </TableCell>
                    </TableRow>
                  );
                  })
                )}
              </TableBody>
            </Table>
          </TableContainer>

          <TablePagination
            component="div"
            count={totalCount}
            page={page}
            onPageChange={(e, newPage) => setPage(newPage)}
            rowsPerPage={rowsPerPage}
            onRowsPerPageChange={(e) => {
              setRowsPerPage(parseInt(e.target.value, 10));
              setPage(0);
            }}
          />
        </CardContent>
      </Card>

      {/* Add Transaction Dialog */}
      <Dialog open={openDialog} onClose={handleCloseDialog} maxWidth="sm" fullWidth>
        <form onSubmit={handleSubmit}>
          <DialogTitle>Add New Recovery Transaction</DialogTitle>
          <DialogContent>
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid item xs={12}>
                <FormControl fullWidth required>
                  <InputLabel>Select Client</InputLabel>
                  <Select
                    name="clientId"
                    value={formData.clientId}
                    onChange={handleChange}
                    label="Select Client"
                  >
                    {clients.map((client) => (
                      <MenuItem key={client.id} value={client.id}>
                        {client.name} - {client.email}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Amount (PKR)"
                  name="amount"
                  type="number"
                  value={formData.amount}
                  onChange={handleChange}
                  required
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Due Date"
                  name="dueDate"
                  type="date"
                  value={formData.dueDate}
                  onChange={handleChange}
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Notes"
                  name="notes"
                  value={formData.notes}
                  onChange={handleChange}
                  multiline
                  rows={3}
                />
              </Grid>
            </Grid>
          </DialogContent>
          <DialogActions>
            <Button onClick={handleCloseDialog}>Cancel</Button>
            <Button type="submit" variant="contained">
              Create
            </Button>
          </DialogActions>
        </form>
      </Dialog>

      {/* Edit Transaction Dialog */}
      <Dialog open={openEditDialog} onClose={() => setOpenEditDialog(false)} maxWidth="sm" fullWidth>
        <form onSubmit={handleEditSubmit}>
          <DialogTitle>Edit Transaction</DialogTitle>
          <DialogContent>
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Amount (PKR)"
                  name="amount"
                  type="number"
                  value={editFormData.amount}
                  onChange={handleEditChange}
                  required
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Due Date"
                  name="dueDate"
                  type="date"
                  value={editFormData.dueDate}
                  onChange={handleEditChange}
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  label="Notes"
                  name="notes"
                  value={editFormData.notes}
                  onChange={handleEditChange}
                  multiline
                  rows={3}
                />
              </Grid>
            </Grid>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setOpenEditDialog(false)}>Cancel</Button>
            <Button type="submit" variant="contained">
              Update
            </Button>
          </DialogActions>
        </form>
      </Dialog>

      {/* Mark Payment Dialog */}
      <Dialog open={openPaymentDialog} onClose={handleClosePaymentDialog} maxWidth="sm" fullWidth>
        <DialogTitle>Mark Payment as Paid</DialogTitle>
        <DialogContent>
          <Grid container spacing={2} sx={{ mt: 1 }}>
            <Grid item xs={12}>
              <Alert severity="info">
                Client: {selectedTransaction?.client?.name}<br />
                Amount: PKR {selectedTransaction?.amount.toFixed(2)}
              </Alert>
            </Grid>
            <Grid item xs={12}>
              <FormControl fullWidth>
                <InputLabel>Payment Method</InputLabel>
                <Select
                  value={paymentData.paymentMethod}
                  onChange={(e) =>
                    setPaymentData({ ...paymentData, paymentMethod: e.target.value })
                  }
                  label="Payment Method"
                >
                  <MenuItem value="manual">Manual</MenuItem>
                  <MenuItem value="gateway">Gateway</MenuItem>
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12}>
              <TextField
                fullWidth
                label="Payment Reference (Optional)"
                value={paymentData.paymentReference}
                onChange={(e) =>
                  setPaymentData({ ...paymentData, paymentReference: e.target.value })
                }
              />
            </Grid>
          </Grid>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleClosePaymentDialog}>Cancel</Button>
          <Button onClick={handleMarkPaid} variant="contained" color="success">
            Mark as Paid & Generate Coins
          </Button>
        </DialogActions>
      </Dialog>

      {/* Bulk Add Dialog */}
      <Dialog open={openBulkDialog} onClose={() => setOpenBulkDialog(false)} maxWidth="md" fullWidth>
        <DialogTitle>Bulk Add Transactions</DialogTitle>
        <DialogContent>
          <Alert severity="info" sx={{ mb: 2 }}>
            Add multiple transactions at once. Only rows with Client and Amount will be created.
          </Alert>
          {bulkData.map((row, index) => (
            <Grid container spacing={2} key={index} sx={{ mb: 2 }}>
              <Grid item xs={12} sm={3}>
                <FormControl fullWidth size="small">
                  <InputLabel>Client</InputLabel>
                  <Select
                    value={row.clientId}
                    onChange={(e) => handleBulkChange(index, 'clientId', e.target.value)}
                    label="Client"
                  >
                    {clients.map((client) => (
                      <MenuItem key={client.id} value={client.id}>
                        {client.name}
                      </MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} sm={2}>
                <TextField
                  fullWidth
                  size="small"
                  label="Amount (PKR)"
                  type="number"
                  value={row.amount}
                  onChange={(e) => handleBulkChange(index, 'amount', e.target.value)}
                />
              </Grid>
              <Grid item xs={12} sm={2}>
                <TextField
                  fullWidth
                  size="small"
                  label="Due Date"
                  type="date"
                  value={row.dueDate}
                  onChange={(e) => handleBulkChange(index, 'dueDate', e.target.value)}
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>
              <Grid item xs={12} sm={4}>
                <TextField
                  fullWidth
                  size="small"
                  label="Notes"
                  value={row.notes}
                  onChange={(e) => handleBulkChange(index, 'notes', e.target.value)}
                />
              </Grid>
              <Grid item xs={12} sm={1}>
                <IconButton
                  color="error"
                  onClick={() => handleRemoveBulkRow(index)}
                  disabled={bulkData.length === 1}
                >
                  <Delete />
                </IconButton>
              </Grid>
            </Grid>
          ))}
          <Button
            startIcon={<Add />}
            onClick={handleAddBulkRow}
            variant="outlined"
            size="small"
          >
            Add Row
          </Button>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpenBulkDialog(false)}>Cancel</Button>
          <Button onClick={handleBulkSubmit} variant="contained">
            Create All Transactions
          </Button>
        </DialogActions>
      </Dialog>
    </div>
  );
};

export default RecoveryTransactionsPage;